---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Create Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/my-blog
    mode: "0644"
  notify: restart nginx

- name: Enable site configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/my-blog
    dest: /etc/nginx/sites-enabled/my-blog
    state: link

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
