---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/my-blog
  notify: restart nginx

- name: Enable site configuration
  file:
    src: /etc/nginx/sites-available/my-blog
    dest: /etc/nginx/sites-enabled/my-blog
    state: link

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
