---
- name: Build and push Docker image
  hosts: localhost
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: ../
          nocache: true
        state: present
        name: nimzy/my-blog
        tag: latest
        source: build
        force_source: true

    - name: Push Docker image to Docker Hub
      community.docker.docker_image:
        name: nimzy/my-blog:latest
        push: true
        source: local
- name: Update website
  hosts: droplet
  become: true
  become_user: root
  tasks:
    - name: Ensure pip3 is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: true
    - name: Ensure Docker Python library is installed
      ansible.builtin.apt:
        name: python3-docker
        state: present
    - name: Ensure Docker socket has correct permissions
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: "0666"
    - name: Pull latest Docker image
      community.docker.docker_image:
        name: nimzy/my-blog:latest
        source: pull
        force_source: true

    - name: Stop and remove existing container
      community.docker.docker_container:
        name: nimzy-my-blog
        state: absent
        force_kill: true

    - name: Recreate container
      community.docker.docker_container:
        name: nimzy-my-blog
        image: nimzy/my-blog:latest
        state: started
        published_ports:
          - "3000:3000"

    - name: Prune dangling images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true
