---
- name: Install Certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Obtain SSL certificate
  ansible.builtin.command: >
    certbot --nginx
    -d {{ domain_name }} -d www.{{ domain_name }}
    --non-interactive --agree-tos
    --email your-email@example.com
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
